# Generated by Django 6.0.3 on 2026-04-14 15:03

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=200)),
                ("password", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=200)),
                (
                    "projects",
                    django_mongodb_backend.fields.ArrayField(
                        base_field=django_mongodb_backend.fields.EmbeddedModelField(
                            embedded_model="mainUI.project"
                        ),
                        blank=True,
                        default=list,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "movies",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=100)),
                ("fileStore", models.JSONField(default=dict)),
                ("mainFile", models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
