# Generated by Django 6.0.3 on 2026-04-14 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainUI", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user",
            table="Users",
        ),
    ]
